In [38]:
import os
import sys
import random

Local IP: 172.31.13.91

In [17]:
import os
import sys
# 프로젝트 루트 디렉토리 설정
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))

    
# HITIT_Server 디렉토리 경로 설정
hitit_server_path = os.path.join(os.getcwd(), '../HITIT_Server')

# 경로 추가
sys.path.append(hitit_server_path)

# 추가된 경로 확인
print("Sys Path:", sys.path)

from mysqlconnect import connect_to_mysql

connection = connect_to_mysql()
cursor = connection.cursor()

Sys Path: ['/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '', '/home/ubuntu/code/DE_ML/HITIT_Server/.venv/lib/python3.12/site-packages', '/home/ubuntu/code/DE_ML/SageMaker/../HITIT_Server', '/home/ubuntu/code/DE_ML/SageMaker/../HITIT_Server']
USER: hitit-user, HOST: hitit-db-mydata.c9oy8g6q0v76.ap-northeast-2.rds.amazonaws.com, PORT: 3306, DATABASE: hitit
Connected to MySQL database

In [17]:
import requests

connection = connect_to_mysql()
cursor = connection.cursor()

def fund_price_crawl(code) :
    global df
    df = pd.DataFrame()
    price_data = []
    results = []
    for page in range(13):
        url = f"https://www.fundguide.net/Api/Fund/GetFundRateGrid?fund_cd={code}&term_gb=12&time_gb=3&page_no={page}&row_cnt=10&_=1718757991716"
        response = requests.get(url, headers={'Content-Type': 'application/json'})
        data = response.json()['Data'][0]
        price_data.extend(data)
    
    for elem in price_data:
        date, price = elem['TRD_DT'],elem['STD_PRC']
        date = date.replace(".","-")
        price = price.replace(",","")
        
        query = f"""INSERT INTO fund_prices (fund_code, Date, price) VALUES ('{code}', '{date}', {price})"""
        cursor.execute(query)
        connection.commit()
        
        # new_elem = pd.DataFrame([{'fund_code': code, "Date": date, "price" : price}])
        # df = pd.concat([df,new_elem],ignore_index=True)
        # print(df)
        # df = pd.DataFrame()

cursor.execute("select fund_code from fund_products_4")
codes = cursor.fetchall()
codes = [ elem[0] for elem in codes]
print(codes)
# for code in codes[112:] :
#     idx = codes.index(code)
#     print(f"{idx}/{len(codes)}")
#     try :
#         fund_price_crawl(code)
#         connection.commit()
#     except :
#         connection.commit()
#         print(f"pass {idx}")
#         continue
#     print(f"{idx} ended")
# connection.close()

hitit-user
Connected to MySQL database

In [7]:
connection = connect_to_mysql()
cursor = connection.cursor()
from datetime import datetime

from pykrx import stock


today = datetime.now() 
today_str = today.strftime('%Y%m%d')
    
print(today_str)

df = stock.get_market_fundamental(today_str)

USER: hitit-user, HOST: hitit-db-mydata.c9oy8g6q0v76.ap-northeast-2.rds.amazonaws.com, PORT: 3306, DATABASE: hitit
Connected to MySQL database
20240621

In [32]:
pers = []
for code, spec in df.iterrows():
    per = spec['PER']
    pers.append(per)
    query = f"UPDATE stocks_products_details SET per = {per} WHERE stock_code = '{code}'"
    print(query)
    try : 
        cursor.execute(query)
    except : 
        print("ERROR occured~")
    connection.commit()
    
# '004800' in df.index
# df.loc['004800',:]
# pers.sort(reverse=True)
# print(pers)

[19100.0, 2835.0, 1497.37, 1170.59, 1139.23, 696.77, 574.36, 523.38, 481.16, 422.14, 344.26, 301.86, 300.88, 278.5, 252.4, 249.38, 236.78, 236.76, 222.93, 218.17, 208.2, 187.69, 183.67, 176.77, 172.16, 169.55, 155.79, 152.57, 129.2, 125.65, 124.28, 114.73, 109.17, 103.53, 98.64, 95.83, 95.17, 94.29, 93.0, 88.42, 85.83, 85.36, 85.29, 83.83, 83.1, 77.62, 73.97, 70.2, 67.95, 65.89, 65.17, 64.63, 63.36, 62.92, 62.51, 61.73, 61.32, 60.0, 56.28, 55.49, 53.88, 51.37, 51.25, 51.0, 49.22, 47.85, 47.59, 47.19, 45.62, 45.62, 45.54, 45.04, 44.52, 44.41, 44.32, 43.23, 43.19, 42.93, 42.64, 42.24, 41.94, 41.51, 41.18, 41.17, 40.92, 40.49, 39.38, 39.34, 38.85, 38.55, 38.52, 37.78, 37.51, 36.71, 35.62, 34.95, 34.43, 31.17, 31.1, 30.34, 29.84, 29.74, 29.71, 29.59, 29.13, 28.88, 28.56, 28.55, 28.46, 28.25, 27.66, 27.53, 27.47, 27.39, 27.23, 27.18, 27.07, 26.81, 26.71, 26.51, 26.27, 26.09, 25.91, 25.75, 25.6, 24.94, 24.69, 24.48, 24.23, 24.23, 24.03, 24.0, 23.84, 23.72, 22.98, 22.88, 22.83, 22.5, 22.34, 21.92, 21.83, 21.68, 21.34, 20.84, 20.63, 20.56, 20.56, 20.38, 19.97, 19.9, 19.85, 19.63, 19.62, 19.48, 19.33, 19.29, 19.23, 19.13, 19.11, 19.08, 19.02, 18.92, 18.82, 18.65, 18.5, 18.45, 18.28, 18.07, 18.04, 18.02, 18.0, 17.83, 17.66, 17.63, 17.54, 17.52, 17.47, 17.45, 17.38, 17.36, 17.29, 17.12, 16.82, 16.7, 16.69, 16.62, 16.61, 16.57, 16.5, 16.49, 16.29, 16.27, 16.09, 15.91, 15.91, 15.78, 15.77, 15.77, 15.72, 15.7, 15.63, 15.57, 15.52, 15.49, 15.49, 15.4, 15.39, 15.31, 15.28, 15.18, 15.06, 15.03, 14.96, 14.86, 14.78, 14.76, 14.71, 14.66, 14.64, 14.58, 14.51, 14.32, 14.28, 14.14, 13.9, 13.72, 13.68, 13.68, 13.66, 13.49, 13.46, 13.43, 13.41, 13.4, 13.17, 13.11, 13.03, 12.9, 12.9, 12.7, 12.58, 12.54, 12.47, 12.35, 12.17, 12.17, 12.03, 12.02, 11.88, 11.88, 11.82, 11.76, 11.73, 11.65, 11.53, 11.53, 11.51, 11.44, 11.43, 11.38, 11.31, 11.29, 11.28, 11.21, 11.19, 11.17, 11.13, 11.11, 11.1, 11.02, 10.97, 10.97, 10.97, 10.93, 10.87, 10.86, 10.77, 10.76, 10.75, 10.71, 10.55, 10.48, 10.47, 10.44, 10.39, 10.37, 10.34, 10.33, 10.27, 10.25, 10.17, 10.13, 10.12, 10.09, 10.0, 9.92, 9.91, 9.83, 9.82, 9.82, 9.82, 9.78, 9.76, 9.71, 9.69, 9.66, 9.53, 9.52, 9.48, 9.43, 9.38, 9.36, 9.33, 9.31, 9.3, 9.3, 9.24, 9.19, 9.19, 9.18, 9.18, 9.17, 9.12, 9.11, 9.06, 9.06, 9.04, 9.03, 8.99, 8.96, 8.93, 8.91, 8.89, 8.87, 8.86, 8.77, 8.77, 8.75, 8.66, 8.65, 8.62, 8.57, 8.56, 8.53, 8.48, 8.47, 8.44, 8.34, 8.31, 8.31, 8.29, 8.23, 8.21, 8.16, 8.05, 7.98, 7.91, 7.9, 7.9, 7.88, 7.83, 7.81, 7.76, 7.76, 7.74, 7.67, 7.62, 7.62, 7.59, 7.5, 7.48, 7.4, 7.38, 7.37, 7.36, 7.36, 7.36, 7.3, 7.3, 7.3, 7.28, 7.27, 7.22, 7.19, 7.19, 7.14, 7.0, 6.99, 6.96, 6.96, 6.9, 6.9, 6.89, 6.88, 6.84, 6.84, 6.83, 6.79, 6.78, 6.78, 6.75, 6.72, 6.65, 6.62, 6.59, 6.59, 6.56, 6.54, 6.49, 6.44, 6.43, 6.42, 6.38, 6.35, 6.32, 6.28, 6.27, 6.26, 6.24, 6.24, 6.18, 6.17, 6.17, 6.14, 6.03, 5.98, 5.97, 5.96, 5.94, 5.91, 5.88, 5.87, 5.87, 5.79, 5.77, 5.76, 5.75, 5.72, 5.72, 5.71, 5.71, 5.69, 5.68, 5.66, 5.56, 5.55, 5.55, 5.54, 5.53, 5.53, 5.49, 5.46, 5.45, 5.45, 5.44, 5.39, 5.39, 5.34, 5.34, 5.32, 5.32, 5.31, 5.3, 5.27, 5.27, 5.26, 5.25, 5.2, 5.2, 5.19, 5.17, 5.16, 5.13, 5.11, 5.1, 5.09, 5.08, 5.01, 4.99, 4.97, 4.96, 4.96, 4.93, 4.92, 4.9, 4.88, 4.86, 4.84, 4.84, 4.83, 4.78, 4.76, 4.72, 4.7, 4.66, 4.64, 4.63, 4.6, 4.59, 4.59, 4.58, 4.58, 4.57, 4.56, 4.55, 4.54, 4.53, 4.44, 4.4, 4.39, 4.35, 4.28, 4.28, 4.28, 4.27, 4.26, 4.25, 4.22, 4.21, 4.2, 4.19, 4.18, 4.15, 4.14, 4.06, 3.97, 3.97, 3.96, 3.95, 3.91, 3.81, 3.8, 3.79, 3.76, 3.7, 3.65, 3.64, 3.59, 3.57, 3.54, 3.54, 3.51, 3.49, 3.49, 3.49, 3.49, 3.46, 3.38, 3.34, 3.34, 3.33, 3.29, 3.27, 3.18, 3.18, 3.17, 3.14, 3.1, 3.04, 3.03, 3.02, 2.99, 2.96, 2.96, 2.9, 2.84, 2.83, 2.79, 2.77, 2.74, 2.71, 2.66, 2.64, 2.61, 2.58, 2.57, 2.5, 2.49, 2.47, 2.44, 2.37, 2.36, 2.08, 2.04, 1.9, 1.89, 1.87, 1.59, 1.28, 0.95, 0.88, 0.37, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [18]:
connection.close()

In [42]:
import requests
url = 'http://172.31.16.127:8080/sentiment'

# 예제 JSON 데이터
data = {"text":"hihi"}

# JSON 데이터를 포함한 POST 요청
response = requests.post(url, json=data, headers={'Content-Type': 'application/json'})

print(response.status_code)  # HTTP 상태 코드 출력  
print(response.json())       # JSON 응답 본문 출력

KeyboardInterrupt:

In [40]:
pers = []
for code, spec in df.iterrows():
    per = spec['PER']
    pers.append(per)
    
    query = f"UPDATE stocks_products_details SET per = {per} WHERE stock_code = '{code}'"
    print(query)
    try : 
        print(code)
        # cursor.execute(query)
    except : 
        print("ERROR occured~")
    connection.commit()
    
# '004800' in df.index
# df.loc['004800',:]
# pers.sort(reverse=True)
# print(pers)

UPDATE stocks_products_details SET per = 12.17 WHERE stock_code = '095570'
095570
UPDATE stocks_products_details SET per = 5.53 WHERE stock_code = '006840'
006840
UPDATE stocks_products_details SET per = 4.4 WHERE stock_code = '027410'
027410
UPDATE stocks_products_details SET per = 9.71 WHERE stock_code = '282330'
282330
UPDATE stocks_products_details SET per = 4.28 WHERE stock_code = '138930'
138930
UPDATE stocks_products_details SET per = 12.54 WHERE stock_code = '001460'
001460
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001465'
001465
UPDATE stocks_products_details SET per = 21.34 WHERE stock_code = '001040'
001040
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '079160'
079160
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '00104K'
00104K
UPDATE stocks_products_details SET per = 9.38 WHERE stock_code = '000120'
000120
UPDATE stocks_products_details SET per = 45.04 WHERE stock_code = '011150'
011150
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '011155'
011155
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001045'
001045
UPDATE stocks_products_details SET per = 16.09 WHERE stock_code = '097950'
097950
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '097955'
097955
UPDATE stocks_products_details SET per = 422.14 WHERE stock_code = '000480'
000480
UPDATE stocks_products_details SET per = 4.64 WHERE stock_code = '000590'
000590
UPDATE stocks_products_details SET per = 13.72 WHERE stock_code = '012030'
012030
UPDATE stocks_products_details SET per = 28.25 WHERE stock_code = '016610'
016610
UPDATE stocks_products_details SET per = 3.81 WHERE stock_code = '005830'
005830
UPDATE stocks_products_details SET per = 8.57 WHERE stock_code = '000990'
000990
UPDATE stocks_products_details SET per = 3.64 WHERE stock_code = '139130'
139130
UPDATE stocks_products_details SET per = 155.79 WHERE stock_code = '001530'
001530
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '000210'
000210
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '000215'
000215
UPDATE stocks_products_details SET per = 7.36 WHERE stock_code = '375500'
375500
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '37550L'
37550L
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '37550K'
37550K
UPDATE stocks_products_details SET per = 2.5 WHERE stock_code = '007340'
007340
UPDATE stocks_products_details SET per = 6.78 WHERE stock_code = '004840'
004840
UPDATE stocks_products_details SET per = 3.97 WHERE stock_code = '155660'
155660
UPDATE stocks_products_details SET per = 5.16 WHERE stock_code = '069730'
069730
UPDATE stocks_products_details SET per = 13.49 WHERE stock_code = '017860'
017860
UPDATE stocks_products_details SET per = 2.08 WHERE stock_code = '017940'
017940
UPDATE stocks_products_details SET per = 5.71 WHERE stock_code = '383220'
383220
UPDATE stocks_products_details SET per = 4.86 WHERE stock_code = '007700'
007700
UPDATE stocks_products_details SET per = 18.28 WHERE stock_code = '114090'
114090
UPDATE stocks_products_details SET per = 3.29 WHERE stock_code = '078930'
078930
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '006360'
006360
UPDATE stocks_products_details SET per = 7.28 WHERE stock_code = '001250'
001250
UPDATE stocks_products_details SET per = 124.28 WHERE stock_code = '007070'
007070
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '078935'
078935
UPDATE stocks_products_details SET per = 3.76 WHERE stock_code = '012630'
012630
UPDATE stocks_products_details SET per = 15.06 WHERE stock_code = '039570'
039570
UPDATE stocks_products_details SET per = 5.55 WHERE stock_code = '089470'
089470
UPDATE stocks_products_details SET per = 6.43 WHERE stock_code = '294870'
294870
UPDATE stocks_products_details SET per = 47.85 WHERE stock_code = '009540'
009540
UPDATE stocks_products_details SET per = 19.29 WHERE stock_code = '267250'
267250
UPDATE stocks_products_details SET per = 7.3 WHERE stock_code = '267270'
267270
UPDATE stocks_products_details SET per = 36.71 WHERE stock_code = '443060'
443060
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '010620'
010620
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '322000'
322000
UPDATE stocks_products_details SET per = 6.89 WHERE stock_code = '042670'
042670
UPDATE stocks_products_details SET per = 41.94 WHERE stock_code = '267260'
267260
UPDATE stocks_products_details SET per = 523.38 WHERE stock_code = '329180'
329180
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '097230'
097230
UPDATE stocks_products_details SET per = 6.26 WHERE stock_code = '014790'
014790
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '003580'
003580
UPDATE stocks_products_details SET per = 14.78 WHERE stock_code = '204320'
204320
UPDATE stocks_products_details SET per = 6.44 WHERE stock_code = '060980'
060980
UPDATE stocks_products_details SET per = 11.53 WHERE stock_code = '011200'
011200
UPDATE stocks_products_details SET per = 6.27 WHERE stock_code = '035000'
035000
UPDATE stocks_products_details SET per = 1.59 WHERE stock_code = '003560'
003560
UPDATE stocks_products_details SET per = 4.88 WHERE stock_code = '175330'
175330
UPDATE stocks_products_details SET per = 6.56 WHERE stock_code = '234080'
234080
UPDATE stocks_products_details SET per = 18.82 WHERE stock_code = '001060'
001060
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001067'
001067
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001065'
001065
UPDATE stocks_products_details SET per = 12.03 WHERE stock_code = '096760'
096760
UPDATE stocks_products_details SET per = 6.88 WHERE stock_code = '105560'
105560
UPDATE stocks_products_details SET per = 9.82 WHERE stock_code = '002380'
002380
UPDATE stocks_products_details SET per = 7.9 WHERE stock_code = '344820'
344820
UPDATE stocks_products_details SET per = 5.2 WHERE stock_code = '009070'
009070
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '009440'
009440
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '119650'
119650
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '092220'
092220
UPDATE stocks_products_details SET per = 109.17 WHERE stock_code = '003620'
003620
UPDATE stocks_products_details SET per = 2.77 WHERE stock_code = '016380'
016380
UPDATE stocks_products_details SET per = 3.51 WHERE stock_code = '001390'
001390
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '033180'
033180
UPDATE stocks_products_details SET per = 9.18 WHERE stock_code = '015590'
015590
UPDATE stocks_products_details SET per = 3.04 WHERE stock_code = '001940'
001940
UPDATE stocks_products_details SET per = 3.57 WHERE stock_code = '025000'
025000
UPDATE stocks_products_details SET per = 2.71 WHERE stock_code = '092230'
092230
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '000040'
000040
UPDATE stocks_products_details SET per = 10.75 WHERE stock_code = '044450'
044450
UPDATE stocks_products_details SET per = 9.11 WHERE stock_code = '030200'
030200
UPDATE stocks_products_details SET per = 11.02 WHERE stock_code = '033780'
033780
UPDATE stocks_products_details SET per = 8.91 WHERE stock_code = '058850'
058850
UPDATE stocks_products_details SET per = 6.14 WHERE stock_code = '058860'
058860
UPDATE stocks_products_details SET per = 4.96 WHERE stock_code = '093050'
093050
UPDATE stocks_products_details SET per = 10.13 WHERE stock_code = '003550'
003550
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '034220'
034220
UPDATE stocks_products_details SET per = 43.23 WHERE stock_code = '051900'
051900
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '051905'
051905
UPDATE stocks_products_details SET per = 63.36 WHERE stock_code = '373220'
373220
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '003555'
003555
UPDATE stocks_products_details SET per = 6.78 WHERE stock_code = '032640'
032640
UPDATE stocks_products_details SET per = 10.76 WHERE stock_code = '011070'
011070
UPDATE stocks_products_details SET per = 27.47 WHERE stock_code = '066570'
066570
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '066575'
066575
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '037560'
037560
UPDATE stocks_products_details SET per = 20.84 WHERE stock_code = '051910'
051910
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '051915'
051915
UPDATE stocks_products_details SET per = 25.6 WHERE stock_code = '079550'
079550
UPDATE stocks_products_details SET per = 9.3 WHERE stock_code = '006260'
006260
UPDATE stocks_products_details SET per = 28.88 WHERE stock_code = '010120'
010120
UPDATE stocks_products_details SET per = 29.59 WHERE stock_code = '000680'
000680
UPDATE stocks_products_details SET per = 236.76 WHERE stock_code = '229640'
229640
UPDATE stocks_products_details SET per = 12.58 WHERE stock_code = '108320'
108320
UPDATE stocks_products_details SET per = 9.19 WHERE stock_code = '001120'
001120
UPDATE stocks_products_details SET per = 7.0 WHERE stock_code = '108670'
108670
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '108675'
108675
UPDATE stocks_products_details SET per = 6.96 WHERE stock_code = '383800'
383800
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '38380K'
38380K
UPDATE stocks_products_details SET per = 8.66 WHERE stock_code = '023150'
023150
UPDATE stocks_products_details SET per = 24.94 WHERE stock_code = '035420'
035420
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '181710'
181710
UPDATE stocks_products_details SET per = 7.81 WHERE stock_code = '005940'
005940
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '005945'
005945
UPDATE stocks_products_details SET per = 98.64 WHERE stock_code = '034310'
034310
UPDATE stocks_products_details SET per = 11.31 WHERE stock_code = '030190'
030190
UPDATE stocks_products_details SET per = 2.57 WHERE stock_code = '008260'
008260
UPDATE stocks_products_details SET per = 7.62 WHERE stock_code = '004250'
004250
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '004255'
004255
UPDATE stocks_products_details SET per = 14.76 WHERE stock_code = '456040'
456040
UPDATE stocks_products_details SET per = 2.44 WHERE stock_code = '010060'
010060
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '178920'
178920
UPDATE stocks_products_details SET per = 16.49 WHERE stock_code = '005490'
005490
UPDATE stocks_products_details SET per = 8.31 WHERE stock_code = '010950'
010950
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '010955'
010955
UPDATE stocks_products_details SET per = 6.84 WHERE stock_code = '034120'
034120
UPDATE stocks_products_details SET per = 8.86 WHERE stock_code = '005090'
005090
UPDATE stocks_products_details SET per = 5.2 WHERE stock_code = '001380'
001380
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '004060'
004060
UPDATE stocks_products_details SET per = 187.69 WHERE stock_code = '001770'
001770
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '002360'
002360
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '009160'
009160
UPDATE stocks_products_details SET per = 3.18 WHERE stock_code = '123700'
123700
UPDATE stocks_products_details SET per = 5.71 WHERE stock_code = '025530'
025530
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '034730'
034730
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '011790'
011790
UPDATE stocks_products_details SET per = 5.08 WHERE stock_code = '018670'
018670
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001740'
001740
UPDATE stocks_products_details SET per = 4.19 WHERE stock_code = '006120'
006120
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '006125'
006125
UPDATE stocks_products_details SET per = 2.74 WHERE stock_code = '210980'
210980
UPDATE stocks_products_details SET per = 172.16 WHERE stock_code = '302440'
302440
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '326030'
326030
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '402340'
402340
UPDATE stocks_products_details SET per = 38.85 WHERE stock_code = '361610'
361610
UPDATE stocks_products_details SET per = 12.9 WHERE stock_code = '100090'
100090
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '03473K'
03473K
UPDATE stocks_products_details SET per = 40.49 WHERE stock_code = '096770'
096770
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '096775'
096775
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '475150'
475150
UPDATE stocks_products_details SET per = 95.17 WHERE stock_code = '001510'
001510
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001515'
001515
UPDATE stocks_products_details SET per = 24.23 WHERE stock_code = '285130'
285130
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '28513K'
28513K
UPDATE stocks_products_details SET per = 10.44 WHERE stock_code = '017670'
017670
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '000660'
000660
UPDATE stocks_products_details SET per = 9.06 WHERE stock_code = '003570'
003570
UPDATE stocks_products_details SET per = 7.36 WHERE stock_code = '064960'
064960
UPDATE stocks_products_details SET per = 9.19 WHERE stock_code = '100840'
100840
UPDATE stocks_products_details SET per = 3.49 WHERE stock_code = '036530'
036530
UPDATE stocks_products_details SET per = 10.0 WHERE stock_code = '005610'
005610
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '011810'
011810
UPDATE stocks_products_details SET per = 51.0 WHERE stock_code = '465770'
465770
UPDATE stocks_products_details SET per = 103.53 WHERE stock_code = '077970'
077970
UPDATE stocks_products_details SET per = 15.31 WHERE stock_code = '071970'
071970
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '002820'
002820
UPDATE stocks_products_details SET per = 4.58 WHERE stock_code = '084870'
084870
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '002710'
002710
UPDATE stocks_products_details SET per = 5.44 WHERE stock_code = '069260'
069260
UPDATE stocks_products_details SET per = 13.46 WHERE stock_code = '007980'
007980
UPDATE stocks_products_details SET per = 3.18 WHERE stock_code = '002900'
002900
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '024070'
024070
UPDATE stocks_products_details SET per = 10.12 WHERE stock_code = '037270'
037270
UPDATE stocks_products_details SET per = 15.72 WHERE stock_code = '000500'
000500
UPDATE stocks_products_details SET per = 9.66 WHERE stock_code = '000860'
000860
UPDATE stocks_products_details SET per = 8.56 WHERE stock_code = '035250'
035250
UPDATE stocks_products_details SET per = 20.56 WHERE stock_code = '011420'
011420
UPDATE stocks_products_details SET per = 9.83 WHERE stock_code = '002100'
002100
UPDATE stocks_products_details SET per = 9.82 WHERE stock_code = '009450'
009450
UPDATE stocks_products_details SET per = 3.8 WHERE stock_code = '267290'
267290
UPDATE stocks_products_details SET per = 9.24 WHERE stock_code = '012320'
012320
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '000050'
000050
UPDATE stocks_products_details SET per = 60.0 WHERE stock_code = '214390'
214390
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '012610'
012610
UPDATE stocks_products_details SET per = 5.17 WHERE stock_code = '009140'
009140
UPDATE stocks_products_details SET per = 2.58 WHERE stock_code = '013580'
013580
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '012200'
012200
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '012205'
012205
UPDATE stocks_products_details SET per = 22.88 WHERE stock_code = '002140'
002140
UPDATE stocks_products_details SET per = 19.11 WHERE stock_code = '010130'
010130
UPDATE stocks_products_details SET per = 7.9 WHERE stock_code = '002240'
002240
UPDATE stocks_products_details SET per = 7.14 WHERE stock_code = '009290'
009290
UPDATE stocks_products_details SET per = 9.33 WHERE stock_code = '017040'
017040
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '017900'
017900
UPDATE stocks_products_details SET per = 5.01 WHERE stock_code = '037710'
037710
UPDATE stocks_products_details SET per = 5.88 WHERE stock_code = '030610'
030610
UPDATE stocks_products_details SET per = 19.08 WHERE stock_code = '339770'
339770
UPDATE stocks_products_details SET per = 42.24 WHERE stock_code = '007690'
007690
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '005320'
005320
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001140'
001140
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '002720'
002720
UPDATE stocks_products_details SET per = 55.49 WHERE stock_code = '083420'
083420
UPDATE stocks_products_details SET per = 9.17 WHERE stock_code = '014530'
014530
UPDATE stocks_products_details SET per = 3.49 WHERE stock_code = '014280'
014280
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '014285'
014285
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '008870'
008870
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001570'
001570
UPDATE stocks_products_details SET per = 125.65 WHERE stock_code = '002990'
002990
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '002995'
002995
UPDATE stocks_products_details SET per = 9.12 WHERE stock_code = '011780'
011780
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '011785'
011785
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '214330'
214330
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '001210'
001210
UPDATE stocks_products_details SET per = 11.88 WHERE stock_code = '073240'
073240
UPDATE stocks_products_details SET per = 19.97 WHERE stock_code = '092440'
092440
UPDATE stocks_products_details SET per = 5.77 WHERE stock_code = '000270'
000270
UPDATE stocks_products_details SET per = 4.28 WHERE stock_code = '024110'
024110
UPDATE stocks_products_details SET per = 24.48 WHERE stock_code = '013700'
013700
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '004540'
004540
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '004545'
004545
UPDATE stocks_products_details SET per = 10.39 WHERE stock_code = '001260'
001260
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '008350'
008350
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '008355'
008355
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '004270'
004270
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '003920'
003920
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '003925'
003925
UPDATE stocks_products_details SET per = 28.56 WHERE stock_code = '025860'
025860
UPDATE stocks_products_details SET per = 6.18 WHERE stock_code = '005720'
005720
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '005725'
005725
UPDATE stocks_products_details SET per = 7.98 WHERE stock_code = '002350'
002350
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '002355'
002355
UPDATE stocks_products_details SET per = 2.04 WHERE stock_code = '092790'
092790
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '251270'
251270
UPDATE stocks_products_details SET per = 7.3 WHERE stock_code = '090350'
090350
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '090355'
090355
UPDATE stocks_products_details SET per = 5.09 WHERE stock_code = '000320'
000320
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '000325'
000325
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '006280'
006280
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '005250'
005250
UPDATE stocks_products_details SET per = 0.0 WHERE stock_code = '005257'
005257

In [ ]:
pers = []
for code, spec in df.iterrows():
    per = spec['PER']
    pers.append(per)
    query = f"UPDATE stocks_products_details SET per = {per} WHERE stock_code = '{code}'"
    print(query)
    try : 
        cursor.execute(query)
    except : 
        print("ERROR occured~")
    connection.commit()
    
# '004800' in df.index
# df.loc['004800',:]
# pers.sort(reverse=True)
# print(pers)

[19100.0, 2835.0, 1497.37, 1170.59, 1139.23, 696.77, 574.36, 523.38, 481.16, 422.14, 344.26, 301.86, 300.88, 278.5, 252.4, 249.38, 236.78, 236.76, 222.93, 218.17, 208.2, 187.69, 183.67, 176.77, 172.16, 169.55, 155.79, 152.57, 129.2, 125.65, 124.28, 114.73, 109.17, 103.53, 98.64, 95.83, 95.17, 94.29, 93.0, 88.42, 85.83, 85.36, 85.29, 83.83, 83.1, 77.62, 73.97, 70.2, 67.95, 65.89, 65.17, 64.63, 63.36, 62.92, 62.51, 61.73, 61.32, 60.0, 56.28, 55.49, 53.88, 51.37, 51.25, 51.0, 49.22, 47.85, 47.59, 47.19, 45.62, 45.62, 45.54, 45.04, 44.52, 44.41, 44.32, 43.23, 43.19, 42.93, 42.64, 42.24, 41.94, 41.51, 41.18, 41.17, 40.92, 40.49, 39.38, 39.34, 38.85, 38.55, 38.52, 37.78, 37.51, 36.71, 35.62, 34.95, 34.43, 31.17, 31.1, 30.34, 29.84, 29.74, 29.71, 29.59, 29.13, 28.88, 28.56, 28.55, 28.46, 28.25, 27.66, 27.53, 27.47, 27.39, 27.23, 27.18, 27.07, 26.81, 26.71, 26.51, 26.27, 26.09, 25.91, 25.75, 25.6, 24.94, 24.69, 24.48, 24.23, 24.23, 24.03, 24.0, 23.84, 23.72, 22.98, 22.88, 22.83, 22.5, 22.34, 21.92, 21.83, 21.68, 21.34, 20.84, 20.63, 20.56, 20.56, 20.38, 19.97, 19.9, 19.85, 19.63, 19.62, 19.48, 19.33, 19.29, 19.23, 19.13, 19.11, 19.08, 19.02, 18.92, 18.82, 18.65, 18.5, 18.45, 18.28, 18.07, 18.04, 18.02, 18.0, 17.83, 17.66, 17.63, 17.54, 17.52, 17.47, 17.45, 17.38, 17.36, 17.29, 17.12, 16.82, 16.7, 16.69, 16.62, 16.61, 16.57, 16.5, 16.49, 16.29, 16.27, 16.09, 15.91, 15.91, 15.78, 15.77, 15.77, 15.72, 15.7, 15.63, 15.57, 15.52, 15.49, 15.49, 15.4, 15.39, 15.31, 15.28, 15.18, 15.06, 15.03, 14.96, 14.86, 14.78, 14.76, 14.71, 14.66, 14.64, 14.58, 14.51, 14.32, 14.28, 14.14, 13.9, 13.72, 13.68, 13.68, 13.66, 13.49, 13.46, 13.43, 13.41, 13.4, 13.17, 13.11, 13.03, 12.9, 12.9, 12.7, 12.58, 12.54, 12.47, 12.35, 12.17, 12.17, 12.03, 12.02, 11.88, 11.88, 11.82, 11.76, 11.73, 11.65, 11.53, 11.53, 11.51, 11.44, 11.43, 11.38, 11.31, 11.29, 11.28, 11.21, 11.19, 11.17, 11.13, 11.11, 11.1, 11.02, 10.97, 10.97, 10.97, 10.93, 10.87, 10.86, 10.77, 10.76, 10.75, 10.71, 10.55, 10.48, 10.47, 10.44, 10.39, 10.37, 10.34, 10.33, 10.27, 10.25, 10.17, 10.13, 10.12, 10.09, 10.0, 9.92, 9.91, 9.83, 9.82, 9.82, 9.82, 9.78, 9.76, 9.71, 9.69, 9.66, 9.53, 9.52, 9.48, 9.43, 9.38, 9.36, 9.33, 9.31, 9.3, 9.3, 9.24, 9.19, 9.19, 9.18, 9.18, 9.17, 9.12, 9.11, 9.06, 9.06, 9.04, 9.03, 8.99, 8.96, 8.93, 8.91, 8.89, 8.87, 8.86, 8.77, 8.77, 8.75, 8.66, 8.65, 8.62, 8.57, 8.56, 8.53, 8.48, 8.47, 8.44, 8.34, 8.31, 8.31, 8.29, 8.23, 8.21, 8.16, 8.05, 7.98, 7.91, 7.9, 7.9, 7.88, 7.83, 7.81, 7.76, 7.76, 7.74, 7.67, 7.62, 7.62, 7.59, 7.5, 7.48, 7.4, 7.38, 7.37, 7.36, 7.36, 7.36, 7.3, 7.3, 7.3, 7.28, 7.27, 7.22, 7.19, 7.19, 7.14, 7.0, 6.99, 6.96, 6.96, 6.9, 6.9, 6.89, 6.88, 6.84, 6.84, 6.83, 6.79, 6.78, 6.78, 6.75, 6.72, 6.65, 6.62, 6.59, 6.59, 6.56, 6.54, 6.49, 6.44, 6.43, 6.42, 6.38, 6.35, 6.32, 6.28, 6.27, 6.26, 6.24, 6.24, 6.18, 6.17, 6.17, 6.14, 6.03, 5.98, 5.97, 5.96, 5.94, 5.91, 5.88, 5.87, 5.87, 5.79, 5.77, 5.76, 5.75, 5.72, 5.72, 5.71, 5.71, 5.69, 5.68, 5.66, 5.56, 5.55, 5.55, 5.54, 5.53, 5.53, 5.49, 5.46, 5.45, 5.45, 5.44, 5.39, 5.39, 5.34, 5.34, 5.32, 5.32, 5.31, 5.3, 5.27, 5.27, 5.26, 5.25, 5.2, 5.2, 5.19, 5.17, 5.16, 5.13, 5.11, 5.1, 5.09, 5.08, 5.01, 4.99, 4.97, 4.96, 4.96, 4.93, 4.92, 4.9, 4.88, 4.86, 4.84, 4.84, 4.83, 4.78, 4.76, 4.72, 4.7, 4.66, 4.64, 4.63, 4.6, 4.59, 4.59, 4.58, 4.58, 4.57, 4.56, 4.55, 4.54, 4.53, 4.44, 4.4, 4.39, 4.35, 4.28, 4.28, 4.28, 4.27, 4.26, 4.25, 4.22, 4.21, 4.2, 4.19, 4.18, 4.15, 4.14, 4.06, 3.97, 3.97, 3.96, 3.95, 3.91, 3.81, 3.8, 3.79, 3.76, 3.7, 3.65, 3.64, 3.59, 3.57, 3.54, 3.54, 3.51, 3.49, 3.49, 3.49, 3.49, 3.46, 3.38, 3.34, 3.34, 3.33, 3.29, 3.27, 3.18, 3.18, 3.17, 3.14, 3.1, 3.04, 3.03, 3.02, 2.99, 2.96, 2.96, 2.9, 2.84, 2.83, 2.79, 2.77, 2.74, 2.71, 2.66, 2.64, 2.61, 2.58, 2.57, 2.5, 2.49, 2.47, 2.44, 2.37, 2.36, 2.08, 2.04, 1.9, 1.89, 1.87, 1.59, 1.28, 0.95, 0.88, 0.37, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]